PROJECT_NAME = "Test with Real Data"
DEBUG = yes
OPTION  = -DRealKind=8
TARGET = TestRealData
OBJECT = MsgManager.o CommonTypes.o CommonUtils.o RunManager.o \
         FloatingPoint.o SphereService.o NFWrap.o SampleManager.o \
         RandomNumber.o DelaunayAndVoronoi.o

include ../../Makefile.basic
