PROJECT_NAME = "Delaunay Triangulation Test Driver"
DEBUG = yes
OPTION  = -DRealKind=8
TARGET = TestDriver TestRealData CompareWithSTRIPACK TestArea
OBJECT = MsgManager.o CommonTypes.o CommonUtils.o RunManager.o \
         FloatingPoint.o SphereService.o NFWrap.o SampleManager.o \
         NFWrap.o RandomNumber.o DelaunayAndVoronoi.o STRIPACK.o

include ../Makefile.basic
