PROJECT_NAME = "Delaunay Triangulation Test Driver"
DEBUG = yes
OPTIONS = #-DOUTPUTSTAGE
TARGET = TestDriver
OBJECT = MsgManager.o CommonTypes.o RunManager.o FloatingPoint.o \
         SphereService.o SampleManager.o NFWrap.o DelaunayAndVoronoi.o

include ../Makefile.basic
