PROJECT_NAME = "Comparison with STRIPACK"
DEBUG = yes
OPTION  = -DRealKind=8
TARGET = CompareWithSTRIPACK
OBJECT = MsgManager.o CommonTypes.o CommonUtils.o RunManager.o \
         FloatingPoint.o SphereService.o NFWrap.o SampleManager.o \
         NFWrap.o RandomNumber.o DelaunayAndVoronoi.o STRIPACK.o

include ../../Makefile.basic
