PROJECT_NAME = "Test Great Circle Arc Intersection"
DEBUG = yes
OPTION = -DRealKind=8
TARGET = TestIntersection
OBJECT = CommonTypes.o MsgManager.o RunManager.o FloatingPoint.o \
         CommonUtils.o SphereService.o

include ../../Makefile.basic
