PROJECT_NAME = "Simple Test"
DEBUG = yes
OPTION  = -DRealKind=8 -DDelaunayAndVoronoi_Debug
TARGET = TestDriver TestArea
OBJECT = MsgManager.o CommonTypes.o CommonUtils.o RunManager.o \
         FloatingPoint.o SphereService.o NFWrap.o SampleManager.o \
         NFWrap.o RandomNumber.o DelaunayAndVoronoi.o

include ../../Makefile.basic
